### PR TITLE
Sync data with upstream

### PR DESCRIPTION
**Pull request by lukhnos**
Cf. https://github.com/openvanilla/McBopomofo/commit/eb28fc4f0a2678f2452c17573cac627cf62122a6

cc @xatier

### CODE REVIEW

**Comment by xatier** [comment]
thank you!

**Comment by tianjianjiang** [comment]
@lukhnos Does this PR being a draft mean it isn't ready for review yet for some reasons?

**Comment by lukhnos** [comment]
> @lukhnos Does this PR being a draft mean it isn't ready for review yet for some reasons?

Ah, right. Should have mentioned that this is pending https://github.com/openvanilla/McBopomofo/pull/477.

**Comment by lukhnos** [comment]
This PR is now ready.

**Review by tianjianjiang — APPROVED** [review]

**Pull request merged**
