### PR TITLE
Fix issues raised by cpplint

### PR DESCRIPTION
**Pull request by xatier**
This PR resolved issues raised by `cpplint`.

I addressed them by categorized in each commit. Here's the list of the change:

- use C++ style `static_cast`
- update `README.md` with linter instructions
- add missing includes
- group `<fstream>` with other standard libs
- fix misuse of <> for gtest
- reorganize filter list with blocklist only and sort with alphabetic order.

A few remarks:

1. These checks are turned off since they have conflicts with clang-format:

`-build/include_alpha,-build/include_order,-build/include_subdir,-whitespace`

2. `readability/nolint` is disabled as `cpplint` doesn't recognize clang-tidy's flag.

```text
src/Engine/UserOverrideModel.cpp:57:  Unknown NOLINT error category: readability-magic-numbers  [readability/nolint] [5]
```

3. disable build/c++11 as chrono is banned by cpplint.

4. disable runtime/references check as it may be controversial. @lukhnos I'm not sure if we'd like to enforce this one?

```text
src/Engine/AssociatedPhrases.h:51:  Is this a non-const reference? If so, make const or use a pointer: std::string_view& k  [runtime/references] [2]
src/Engine/AssociatedPhrases.h:51:  Is this a non-const reference? If so, make const or use a pointer: std::string_view& v  [runtime/references] [2]
```

### CODE REVIEW

**Comment by lukhnos** [comment]
Thanks again for working on this!

Re: disable runtime/references check as it may be controversial. Actually that check makes a lot of sense. For `std::striing_view` though, now I think about it, we should use pass-by-value, and then the entire `Row` struct in question can be turned into an immutable type:

```cpp
    #include <utilitiy>

    struct Row {
        Row(std::string_view k, std::string_view v)
            : key(std::move(k))
            , value(std::move(v))
        {
        }
        const std::string_view key;
        const std::string_view value;
    };
```

(For such a small type, there's probably no difference in using `std::move` since complier may already have elided it—a quick https://godbolt.org/ run confirms so—though it's likely a good habit to use the move semantics in a type-agnostic manner.)

**Comment by xatier** [comment]
Thanks for the feedback. Personally, I'm fine with having non-const references, as I read them with semantics that these parameters are mutable (aka output parameters), and yet they cannot be null. 

Converting them to pointers does provide a stronger meaning that they are indeed mutable (as well as the need to add null checks around them). Some may also suggest it'd be even better to wrap them around smart pointers, or the use of rvalue references `std::string_view&&` (which is also another somewhat controversial topic, IMO).

Here's the Google style guide's section on this:

https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

Here's the list of all occurrence on this:

```
src/Engine/AssociatedPhrases.h:51:  Is this a non-const reference? If so, make const or use a pointer: std::string_view& k  [runtime/references] [2]
src/Engine/AssociatedPhrases.h:51:  Is this a non-const reference? If so, make const or use a pointer: std::string_view& v  [runtime/references] [2]

src/Engine/Mandarin/Mandarin.cpp:34:  Is this a non-const reference? If so, make const or use a pointer: std::string& target  [runtime/references] [2]

src/Engine/McBopomofoLM.h:120:  Is this a non-const reference? If so, make const or use a pointer: std::unordered_set<std::string>& insertedValues  [runtime/references] 
[2] 

src/Engine/ParselessLMBenchmark.cpp:38:  Is this a non-const reference? If so, make const or use a pointer: benchmark::State& state  [runtime/references] [2]
src/Engine/ParselessLMBenchmark.cpp:49:  Is this a non-const reference? If so, make const or use a pointer: benchmark::State& state  [runtime/references] [2]

src/Engine/UserPhrasesLM.h:50:  Is this a non-const reference? If so, make const or use a pointer: std::string_view& k  [runtime/references] [2]
src/Engine/UserPhrasesLM.h:50:  Is this a non-const reference? If so, make const or use a pointer: std::string_view& v  [runtime/references] [2]
src/UTF8Helper.cpp:37:  Is this a non-const reference? If so, make const or use a pointer: std::string::const_iterator& i  [runtime/references] [2]
```

**Comment by xatier** [comment]
A few open issues on the `cpplint` side for your reference. Basically, Google's style guides used to ban non-const refs, but they later allowed it, the public `cpplint` doesn't reflect this yet.

https://github.com/google/styleguide/issues/563
https://github.com/google/styleguide/commit/7a7a2f510efe7d7fc5ea8fbed549ddb31fac8f3e#diff-26120df7bca3279afbf749017c778545
https://github.com/cpplint/cpplint/issues/148

**Comment by xatier** [comment]
Re: `readability/nolint is disabled as cpplint doesn't recognize clang-tidy's flag.`

I posted a PR to `cpplint`, but it doesn't seem that they are taking PRs actively, we may still need to disable this check for a little longer.

https://github.com/cpplint/cpplint/pull/231

**Comment by lukhnos** [comment]
> Here's the list of all occurrence on this [non-const reference uses]:

Ah. Thanks for listing them all. I now realized that we do have more than one place where we do *mutate* arguments, especially making them "output parameters".

At this point I think that we should take your PR as is, keeping the cpplint suppressions in README. What do you think?

And after the PR, I think we should discuss the following:

1. Re non-const reference parameters: should we just ban them, and change existing uses to non-const pointers?
2. Should we continue recommending the use of cpplint in README, or should we make it clear that it's a nice-to-have? It seems there is still a lot of value in using it even if it comes with issues (not always agreeing it with clang-format, and the state of the project means some inevitable gaps in its coverage), but on the other hand it's just one more thing to keep track of. WDYT?

**Review by lukhnos — APPROVED** [review]

**Comment by xatier** [comment]
Thanks for the prompt reply!

1. Personally, I would prefer to continue using non-const references as I see them with clear hint that this parameter is mutable. Additionally, one can use move semantics optionally when it makes more sense (and when with clear syntax), avoid too complicated syntax/implicit C++ semantics when possible (e.g., `std::forward` and `decltype`, etc.) to reduce mental effort of tracking them.

2. I'd like to keep the current wording for the use of the linters, which sounds a) one `should` use `clang-format` before submitting PRs, and b) running `cpplint` and `clang-tidy` are nice-to-have. I don't feel a strong need to make them mandatory (such as checking them in CIs) as we don't usually have active PRs/frequent commits to this project, this reduces some frictions for new contributors. Kindly let me know if the current wording in README sounds the same, or it's ambiguous to you. I'd be happy to help update the README.

**Comment by lukhnos** [comment]
> Thanks for the prompt reply!
> 1. Personally, I would prefer to continue using non-const references as I see them with clear hint that this parameter is mutable. […] Additionally, one can use move semantics optionally when it makes more sense (and when with clear syntax), avoid too complicated syntax/implicit C++ semantics when possible (e.g., `std::forward` and `decltype`, etc.) to reduce mental effort of tracking them.
> 2. I'd like to keep the current wording for the use of the linters, which sounds a) one `should` use `clang-format` before submitting PRs, and b) running `cpplint` and `clang-tidy` are nice-to-have. […]

Makes sense. LGTM!

**Pull request merged**
