### PR TITLE
feat(macro): add Japanese calendar macro support

### PR DESCRIPTION
**Pull request by xatier**
This commit adds the following macros:

DATE_TODAY_MEDIUM_JAPANESE
DATE_TOMORROW_MEDIUM_JAPANESE
DATE_YESTERDAY_MEDIUM_JAPANESE

Also fix a few clang-tidy warnings.

### CODE REVIEW

**Comment by xatier** [comment]
@lukhnos small feature that extends @zonble's awesome work. Please kindly take a look.

**Comment by xatier** [comment]
screenshots from my local build.

**Review by lukhnos — APPROVED** [review]
LGTM. Thanks for making another clang-tidy pass too.

**Comment by lukhnos** [comment]
I'm putting the merge on hold now. We'll need to have the macOS equivalent of the macros. Then we can sync `data.txt` from upstream without worring that the macros will be removed at the next update.

**Comment by xatier** [comment]
no worries, take your time!

**Comment by xatier** [comment]
@lukhnos I actually wonder if we should also add the macros to `今天` as well. I had this idea inspired by `mozc`, when saying きょう (今日), it shows 

image

**Comment by xatier** [comment]
@lukhnos, I noticed `replacement` is mostly repetitive, I have another refactoring commit after this PR. I'll rebase and open a new one once this PR is merged.

https://github.com/xatier/fcitx5-mcbopomofo/commit/35e297e4b1e365647fa8ed54324c5e42b739d338

**Pull request merged**
